openapi: "3.0.3"
info:
  title: OpenAPI Sample Project
  version: "1.0"
servers:
  - url: http://localhost:8080

paths:
  /books:
    get:
      description: books listing
      responses:
        "200":
          description: list of books
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/BookList"

components:
  schemas:
    BookList:
      properties:
        books:
          type: array
          items:
            $ref: "#/components/schemas/Book"
    Book:
      type: object
      properties:
        author:
          type: string
        title:
          type: string
        series:
          type: integer
