openapi: "3.0.3"
info:
  title: OpenAPI Sample Project
  version: "1.0"
servers:
  - url: http://localhost:8080

paths:
  /books:
    get:
      description: books listing
      x-handler-args:
        - arg: javax.servlet.http.HttpServletRequest request
        - arg: org.springframework.web.util.UriComponentsBuilder builder
          last: true
      parameters:
        - name: max
          in: query
          schema:
            type: integer
      responses:
        "200":
          description: list of books
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/BookListModel"
    post:
      description: bookを登録する(description)
      summary: book登録(summary)
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/BookModel"
      responses:
        "200":
          description: "登録したbook"
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/BookModel"
  /books/{id}:
    get:
      description: books listing
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: book
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/BookModel"

components:
  schemas:
    BookListModel:
      properties:
        books:
          type: array
          items:
            $ref: "#/components/schemas/BookModel"
    BookModel:
      type: object
      properties:
        author:
          type: string
        title:
          type: string
        series:
          type: integer
