/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;

public class App {

    public static void main(String[] args) {
        var child1 = new ChildEntityDto();
        child1.setName("child 1");
        var child2 = new ChildEntityDto();
        child2.setName("child 2");
        var children = List.of(child1, child2);

        var dto = new MyEntityDto();
        dto.setName("my entity");
        dto.setChildren(children);

        var entity = MyEntityMapper.Companion.getINSTANCE().toEntity(dto);
        System.out.println("Entity: " + entity.toString());
    }
}
