server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        provider:
          mykeycloak:
            # https://www.keycloak.org/docs/latest/securing_apps/index.html#endpoints-2
            # http://localhost:8080/auth/realms/myrealm/.well-known/openid-configuration
            issuer-uri: http://localhost:8080/auth/realms/myrealm
            user-name-attribute: preferred_username
        registration:
          myspring:
            authorization-grant-type: authorization_code
            # 上で定義しているprovider名
            provider: mykeycloak
            # keycloakに登録したidと対応するsecret
            # http://localhost:8080/auth/admin/master/console/#/realms/myrealm/clients
            client-id: myclient
            client-secret: 50200bc7-7a3e-4505-a2de-7677511ba10e
