insert into oauth_client_details (
  client_id,
  resource_ids,
  client_secret,
  scope,
  authorized_grant_types,
  web_server_redirect_uri,
  authorities,
  access_token_validity,
  refresh_token_validity,
  additional_information,
  autoapprove
)
values
(
  'first-client',
  null,
  '{noop}noonewilleverguess',
  'read',
  'authorization_code,refresh_token',
  'http://localhost:8081/client/tasks',
  null,
  60,
  6000000,
  null,
  'read'
);
